### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by jannisborn** [ropensci/medrxivr#26]
It seems like the bioRxiv/medRxiv API are down entirely. I'm experiencing the following error with every request:
`Error : (2002) Connection refused`

Can you confirm this? All examples provided in the docs (https://api.biorxiv.org) are failing. 
For example: https://api.biorxiv.org/details/biorxiv/2018-08-21/2018-08-28/45 results in the described error.

Are you experiencing the same? Posting here, since it might affect your entire package.

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by mcguinlu** [comment]
Hi @jannisborn, 

Thanks so much for flagging this - can confirm that it is not just you, the API seems to be down entirely. 🤦‍♂️ CRAN have also been on to flag that the API being unavailble has caused the test suite to fail, so that's three-way validation. I've [reached out to the people behind medRxiv](https://twitter.com/mcguinlu/status/1361244816898744321?s=20), and will post back once I hear. 

 In the meantime, you might just have to wait it out - sorry about this, but the package is (as you might expect!) fairly reliant on the API being up. 

One other option if you are trying to search medRxiv is to use the maintained medRxiv snapshot via `mx_snapshot()` - the last snapshot was taken on the 13th Feb, so it looks like the API has been down for the weekend (as the snapshots are automatically taken from the API every morning). See the [Data sources"](https://github.com/ropensci/medrxivr#medrxiv-data) section of the README for more details.

**Comment by jannisborn** [comment]
Thanks a lot for the swift reply @mcguinlu!
I also contacted the biorxiv team directly and here's their reply:

```
Dear Jannis Born,


Thank you for contacting us. We are experiencing problems with the database. 
Our technicians are working on resolving this as quickly as they can.


The bioRxiv Team
```

The `mx_snapshot` is indeed a great pointer. Thanks!

Let's keep commenting here as updates come in.

**Comment by mcguinlu** [comment]
Right, the API seems to be up and running again now: https://api.biorxiv.org/details/biorxiv/2018-08-21/2018-08-28/45

I'm going to close this issue now, but thanks again for flagging it @jannisborn!
